# Generated by Django 5.1.1 on 2024-10-04 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_profile_age_profile_date_of_birth_and_more'), ('users', '0003_alter_profile_doctors_name_and_more'), ('users', '0004_alter_profile_phone_number'), ('users', '0005_remove_profile_first_name_remove_profile_last_name')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('doctors_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('medication_regimen', models.TextField(blank=True, null=True)),
                ('next_appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
