# Generated by Django 5.1.1 on 2024-10-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0005_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_entities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
